
#define THREAD_PRIO_STARTUP					56
#define THREAD_PRIO_IDLE					63
//#define  OS_TASK_IDLE_PRIO  (OS_LOWEST_PRIO)
//#define OS_LOWEST_PRIO					63

//#define OS_TASK_IDLE_STK_SIZE				0x400
#define THREAD_STACK_SIZE_STARTUP			0x320


